// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8pIGuJ1ThelZd1-J6hi4gm8ftvBHiFs',
    appId: '1:618589870198:web:0af5b669e3d266aba5a757',
    messagingSenderId: '618589870198',
    projectId: 'oyna-79aae',
    authDomain: 'oyna-79aae.firebaseapp.com',
    storageBucket: 'oyna-79aae.firebasestorage.app',
    measurementId: 'G-5TLE9Y36BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-OS8zGy0ss9YfYtGMGNiifC6V0l6XuEs',
    appId: '1:618589870198:android:113d18cee49032eca5a757',
    messagingSenderId: '618589870198',
    projectId: 'oyna-79aae',
    storageBucket: 'oyna-79aae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLX6B6qjnXapAgAzP7ecItOhoCiV5KxMw',
    appId: '1:618589870198:ios:896a74ec567af74aa5a757',
    messagingSenderId: '618589870198',
    projectId: 'oyna-79aae',
    storageBucket: 'oyna-79aae.firebasestorage.app',
    androidClientId: '618589870198-7tvpautdj9pb6ttc7s10qo9ttd9arr1r.apps.googleusercontent.com',
    iosClientId: '618589870198-rheggnout9483p1rvee87qrkkgmjf4g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLX6B6qjnXapAgAzP7ecItOhoCiV5KxMw',
    appId: '1:618589870198:ios:896a74ec567af74aa5a757',
    messagingSenderId: '618589870198',
    projectId: 'oyna-79aae',
    storageBucket: 'oyna-79aae.firebasestorage.app',
    androidClientId: '618589870198-7tvpautdj9pb6ttc7s10qo9ttd9arr1r.apps.googleusercontent.com',
    iosClientId: '618589870198-rheggnout9483p1rvee87qrkkgmjf4g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH8pIGuJ1ThelZd1-J6hi4gm8ftvBHiFs',
    appId: '1:618589870198:web:def3691d2150a770a5a757',
    messagingSenderId: '618589870198',
    projectId: 'oyna-79aae',
    authDomain: 'oyna-79aae.firebaseapp.com',
    storageBucket: 'oyna-79aae.firebasestorage.app',
    measurementId: 'G-T4Q2PHK6LW',
  );

}