name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Backend/**'
      - '.github/**'
  workflow_dispatch: {} # Manual işə salmaq üçün düymə əlavə edir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH commands to deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/OynaAdminPanel
            git stash
            git pull
            cd Backend
            npm install
            npm run build
            pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
            pm2 save
